<?php
/**
 * Vue Backend Login Prompt
 * Formulaire de login pour la partie Backend
 * @author : kryzaal
 * @package : Truffes
 */
 
/* Initialisation du translator */
$translator = new Zend_View_Helper_Translate();
?>

<!-- Message de login -->
<h2><?=$translator->translate("must_login")?></h2>


<?php if(!empty($this->error)):?>
<!-- En cas d'erreur -->
    <p><?=$translator->translate($this->error)?></p>
<?php endif ?>

<!-- Le formulaire -->
<?= $this->form ?>