<h3>Error has happened. Inside this application. Sorry about that.</h3>
<p><?=$this->message ?> (<?=$this->code ?>) </p>
<?
 if ( isset($this->info ) ) { ?>
<? if ( 404 == $this->code ) { ?>
  <p><b>Reason:</b> <?= $this->info ?></p>
<? } elseif (500 == $this->code) { ?>
  <p>Bad server, naughty server!<br />No donut for you!</p>
  <h4>Exception information:</h4>
 <p><b>Message:</b> <?php
 echo $this->info->getMessage() . "<br/>";
 $element = $this->info;
 while(null != $element->getPrevious()) {
     $element = $element->getPrevious();
     echo "&nbsp;&nbsp;&nbsp;&nbsp;#Previous : " . $element->getMessage() . "<br/>";
 }
 ?></p>
 <h4>Stack trace:</h4>
 <pre><?= $this->info->getTraceAsString() ?></pre>
<? } ?>
<? } ?>